name = "vayroai"
main = "src/index.ts"
compatibility_date = "2026-09-01"
workers_dev = true

[vars]
APP_NAME = "VayroAI"

[[d1_databases]]
binding = "DB"
database_name = "vayroai-db"
database_id = "e4ca6874-b93f-40b3-b5a4-06394511245f"
migrations_dir = "migrations"

[ai]
binding = "AI"


[triggers]
crons = ["* * * * *"]
