import type { Env } from '../env';
import type { User, Chat, Model, Plan } from '../db/types';
import * as repo from '../db/repo';
import { t, type Lang } from '../i18n';
import { ik, type InlineKeyboard } from '../telegram/markup';
import { TelegramApi } from '../telegram/api';
import { formatRub } from '../utils/text';
import { IMAGE_TEMPLATES } from '../image/service';

export async function sendOrEditUi(api:TelegramApi,db:D1Database,user:User,text:string,keyboard:InlineKeyboard|undefined,replyRows:string[][]=[],sourceMessageId?:number){
  const opts:Record<string,unknown>={parse_mode:'HTML',disable_web_page_preview:true, ...(keyboard?{reply_markup:ik(keyboard)}:{})};
  const target=sourceMessageId??user.ui_message_id??undefined;
  if(target){try{await api.editMessageText(user.id,target,text,opts);await db.prepare('UPDATE users SET ui_message_id=? WHERE id=?').bind(target,user.id).run();return target}catch{}}
  const msg=await api.sendMessage(user.id,text,{...opts, ...(replyRows.length?{reply_markup:replyRows}:{})});
  await db.prepare('UPDATE users SET ui_message_id=? WHERE id=?').bind(msg.message_id,user.id).run();
  return msg.message_id;
}

function chatPageRows(user:User,chats:Chat[],page:number,total:number,kind:'active'|'archive'){const rows=chats.map(c=>[{text:`${c.title.slice(0,52)}`,callback_data:`chat:view:${c.id}`}]);const nav:any[]=[];if(page>1)nav.push({text:t(user.language,'back'),callback_data:`${kind==='active'?'chats':'archive'}:page:${page-1}`});if(page<total)nav.push({text:t(user.language,'next'),callback_data:`${kind==='active'?'chats':'archive'}:page:${page+1}`});if(nav.length)rows.push(nav);return rows}

export async function mainMenu(api:TelegramApi,db:D1Database,env:Env,user:User,chat:Chat,sourceMessageId?:number){
 const model=await repo.getUsableModel(db,chat.model_key,env)??await repo.getDefaultChatModel(db,env);const count=await repo.countLiveMessages(db,chat.id,user.id);
 const text=[t(user.language,'menu_title'),t(user.language,'chat_model',{model:model?.name??chat.model_key}),count?t(user.language,'live_messages',{count}):t(user.language,'no_messages')].join('\n\n');
 const rows:InlineKeyboard=[[{text:t(user.language,'menu_chat'),callback_data:'chat:open'},{text:t(user.language,'change_model'),callback_data:'models:open'}],[{text:t(user.language,'new_chat'),callback_data:'chat:new'},{text:t(user.language,'my_chats'),callback_data:'chats:open'}],[{text:t(user.language,'images'),callback_data:'image:open'},{text:t(user.language,'tools'),callback_data:'tools:open'}],[{text:t(user.language,'account'),callback_data:'account:open'},{text:t(user.language,'help'),callback_data:'help:open'}]];
 return sendOrEditUi(api,db,user,text,rows,[],sourceMessageId);
}

export async function modelScreen(api:TelegramApi,db:D1Database,env:Env,user:User,chat:Chat,sourceMessageId?:number){
 const current=await repo.modelByKey(db,chat.model_key);const families=await repo.listUsableChatFamilies(db,env);const text=[t(user.language,'current_model',{model:current?.name??chat.model_key}),t(user.language,'chat_model_family',{title:chat.title,family:current?.family??'—'}),'\n'+t(user.language,'daily')+'\n'+t(user.language,'daily_desc'),'\n'+t(user.language,'advanced')+'\n'+t(user.language,'advanced_desc'),t(user.language,'model_cost_note')].join('\n');
 const rows:any[]=[];for(let i=0;i<families.length;i+=2)rows.push(families.slice(i,i+2).map(f=>({text:f.family,callback_data:`family:${encodeURIComponent(f.family)}`})));rows.push([{text:t(user.language,'back_chat'),callback_data:'chat:open'}]);
 return sendOrEditUi(api,db,user,text,rows,[],sourceMessageId);
}
export async function familyScreen(api:TelegramApi,db:D1Database,env:Env,user:User,chat:Chat,family:string,sourceMessageId?:number){
 const models=await repo.listModelsForFamily(db,env,family);const rows:any[]=[];for(let i=0;i<models.length;i+=2)rows.push(models.slice(i,i+2).map(m=>({text:`${repo.modelEmoji(m)} ${m.name} · ${m.cost}`,callback_data:`model:set:${encodeURIComponent(m.model_key)}`})));rows.push([{text:t(user.language,'back'),callback_data:'models:open'}]);
 return sendOrEditUi(api,db,user,`<b>${escape(family)}</b>\n\n${models.map(m=>`${repo.modelEmoji(m)} <b>${escape(m.name)}</b> · ${m.cost}`).join('\n')||'—'}`,rows,[],sourceMessageId);
}
function escape(s:string){return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}

export async function chatsScreen(api:TelegramApi,db:D1Database,user:User,page=1,sourceMessageId?:number){const size=5,total=Math.max(1,Math.ceil((await repo.countChats(db,user.id,false))/size));const p=Math.min(Math.max(1,page),total);const chats=await repo.listChats(db,user.id,false,p,size);const rows=chatPageRows(user,chats,p,total,'active');rows.push([{text:t(user.language,'archive_title').replace(/<[^>]+>/g,''),callback_data:'archive:open'},{text:t(user.language,'back_chat'),callback_data:'chat:open'}]);const text=t(user.language,'chats_title')+'\n\n'+(chats.length?chats.map((c,i)=>`${(p-1)*size+i+1}. ${escape(c.title)}`).join('\n'):t(user.language,'no_chats'))+`\n\n${t(user.language,'page_of',{page:p,total})}`;return sendOrEditUi(api,db,user,text,rows,[],sourceMessageId)}
export async function archiveScreen(api:TelegramApi,db:D1Database,user:User,page=1,sourceMessageId?:number){const size=5,total=Math.max(1,Math.ceil((await repo.countChats(db,user.id,true))/size));const p=Math.min(Math.max(1,page),total);const chats=await repo.listChats(db,user.id,true,p,size);const rows=chatPageRows(user,chats,p,total,'archive');rows.push([{text:t(user.language,'my_chats'),callback_data:'chats:open'},{text:t(user.language,'back_chat'),callback_data:'chat:open'}]);const text=t(user.language,'archive_title')+'\n\n'+(chats.length?chats.map((c,i)=>`${(p-1)*size+i+1}. ${escape(c.title)}`).join('\n'):t(user.language,'archive_empty'))+`\n\n${t(user.language,'page_of',{page:p,total})}`;return sendOrEditUi(api,db,user,text,rows,[],sourceMessageId)}
export async function chatActionsScreen(api:TelegramApi,db:D1Database,user:User,chat:Chat,sourceMessageId?:number){const text=`<b>${escape(chat.title)}</b>\n\n${chat.is_archived?t(user.language,'archive_hint'):t(user.language,'chat_model',{model:chat.model_key})}`;const rows=chat.is_archived?[[{text:t(user.language,'continue'),callback_data:`chat:continue:${chat.id}`}],[{text:t(user.language,'rename'),callback_data:`chat:rename:${chat.id}`},{text:t(user.language,'delete'),callback_data:`chat:delete:${chat.id}`}],[{text:t(user.language,'back'),callback_data:'archive:open'}]]:[[ {text:t(user.language,'archive'),callback_data:`chat:archive:${chat.id}`},{text:t(user.language,'rename'),callback_data:`chat:rename:${chat.id}`}],[{text:t(user.language,'delete'),callback_data:`chat:delete:${chat.id}`}],[{text:t(user.language,'back'),callback_data:'chats:open'}]];return sendOrEditUi(api,db,user,text,rows,[],sourceMessageId)}

export async function accountScreen(api:TelegramApi,db:D1Database,user:User,sourceMessageId?:number){const bal=await repo.getBalance(db,user.id);const stats=await repo.getUserStats(db,user.id);const sub=await repo.getActiveSubscription(db,user.id);const active=await repo.countChats(db,user.id,false);const archived=await repo.countChats(db,user.id,true);const limit= sub?.plan?.points&&sub.plan.points>0?sub.plan.points:Number((await repo.getSetting(db,'free_points_daily'))??50);const subText=sub?.plan?t(user.language,'subscription_info',{plan:user.language==='ru'?sub.plan.title_ru:sub.plan.title_en,days:Math.max(0,Math.ceil((new Date(sub.expires_at).getTime()-Date.now())/86400000)),points:sub.plan.points||100}):t(user.language,'subscription_none');const text=[t(user.language,'account_title'),t(user.language,'tg_id',{id:user.id}),t(user.language,'daily_points',{n:bal.free,limit}),t(user.language,'bonus_points',{n:bal.paid}),subText,t(user.language,'dialogs_info',{active,archived}),t(user.language,'stats_info',{today:stats.responsesToday,total:stats.totalResponses})].join('\n\n');const rows=[[{text:t(user.language,'plans'),callback_data:'plans:open'},{text:t(user.language,'orders'),callback_data:'orders:open'}],[{text:t(user.language,'language',{lang:user.language==='ru'?'Русский':user.language==='uz'?'O‘zbekcha':'English'}),callback_data:'language:open'},{text:t(user.language,'back_chat'),callback_data:'chat:open'}]];return sendOrEditUi(api,db,user,text,rows,[],sourceMessageId)}

export async function rolesScreen(api:TelegramApi,db:D1Database,user:User,sourceMessageId?:number){const roles=await repo.listRoles(db);const chat=user.current_chat_id?await repo.getChat(db,user.current_chat_id,user.id):null;const uzNames:any={assistant:'Yordamchi',editor:'Muharrir',translator:'Tarjimon',teacher:'O‘qituvchi',programmer:'Dasturchi'};const rows=roles.map(r=>[{text:user.language==='ru'?r.name_ru:user.language==='uz'?(uzNames[r.role_key]??r.name_en):r.name_en,callback_data:`role:set:${r.role_key}`}]);if(chat?.role_key||chat?.custom_role)rows.push([{text:'🧹 Сбросить роль',callback_data:'role:reset'}]);rows.push([{text:t(user.language,'custom_role'),callback_data:'role:custom'}],[{text:t(user.language,'back_chat'),callback_data:'chat:open'}]);return sendOrEditUi(api,db,user,t(user.language,'roles_title')+'\n\n'+t(user.language,'roles_hint'),rows,[],sourceMessageId)}

export async function searchScreen(api:TelegramApi,db:D1Database,env:Env,user:User,sourceMessageId?:number){if(Number((await repo.getSetting(db,'feature_search'))??1)===0)return sendOrEditUi(api,db,user,t(user.language,'search_title')+'\n\n'+t(user.language,'no_search_models'),[[{text:t(user.language,'back_chat'),callback_data:'chat:open'}]],[],sourceMessageId);const models=await repo.listSearchModels(db,env);if(!models.length)return sendOrEditUi(api,db,user,t(user.language,'search_title')+'\n\n'+t(user.language,'no_search_models'),[[{text:t(user.language,'back_chat'),callback_data:'chat:open'}]],[],sourceMessageId);const rows=models.map(m=>[{text:`${user.search_model_key===m.model_key?'✅ ':''}${repo.modelEmoji(m)} ${m.name} · ${m.cost}`,callback_data:`search:set:${encodeURIComponent(m.model_key)}`}]);rows.push([{text:t(user.language,'search_back'),callback_data:'search:back'}]);return sendOrEditUi(api,db,user,t(user.language,'search_title')+'\n\n'+t(user.language,'search_hint'),rows,[],sourceMessageId)}

const planTitle=(u:User,p:Plan)=>u.language==='ru'?p.title_ru:p.title_en;
export async function plansScreen(api:TelegramApi,db:D1Database,user:User,sourceMessageId?:number){const plans=await repo.listPlans(db,'subscription');const wanted=plans.filter(p=>['sub-1w','sub-1m'].includes(p.plan_key));const rows=wanted.map(p=>[{text:`${planTitle(user,p)} · ${formatRub(p.price_minor)} ₽`,callback_data:`plan:detail:${p.plan_key}`}]);rows.push([{text:t(user.language,'all_plans'),callback_data:'plans:all'}],[{text:t(user.language,'orders'),callback_data:'orders:open'}],[{text:t(user.language,'back_chat'),callback_data:'chat:open'}]);return sendOrEditUi(api,db,user,t(user.language,'plans_title')+'\n\n'+wanted.map(p=>`${planTitle(user,p)} · ${formatRub(p.price_minor)} ₽`).join('\n'),rows,[],sourceMessageId)}
export async function allPlansScreen(api:TelegramApi,db:D1Database,user:User,sourceMessageId?:number){const plans=await repo.listPlans(db,'subscription');const rows=plans.map(p=>[{text:`${planTitle(user,p)} · ${formatRub(p.price_minor)} ₽`,callback_data:`plan:detail:${p.plan_key}`}]);rows.push([{text:t(user.language,'orders'),callback_data:'orders:open'}],[{text:t(user.language,'back'),callback_data:'plans:open'}]);return sendOrEditUi(api,db,user,t(user.language,'plans_title'),rows,[],sourceMessageId)}
export async function planDetailsScreen(api:TelegramApi,db:D1Database,user:User,planKey:string,sourceMessageId?:number){const p=await repo.getPlan(db,planKey);if(!p)return;const points=p.points||100;const archive=p.duration_days&&p.duration_days>=30?48:24;const images=t(user.language,'plan_images_yes');const text=t(user.language,'plan_details',{name:planTitle(user,p),price:formatRub(p.price_minor),points,archive:archive===48?t(user.language,'plan_archive_48'):t(user.language,'plan_archive_24'),images});const rows=[[{text:t(user.language,'buy'),callback_data:`plan:create:${p.plan_key}`}],[{text:t(user.language,'my_account'),callback_data:'account:open'},{text:t(user.language,'back'),callback_data:'plans:all'}]];return sendOrEditUi(api,db,user,text,rows,[],sourceMessageId)}
export async function pointPlansScreen(api:TelegramApi,db:D1Database,user:User,sourceMessageId?:number){return plansScreen(api,db,user,sourceMessageId)}
export async function ordersScreen(api:TelegramApi,db:D1Database,user:User,sourceMessageId?:number){const orders=await repo.listUserOrders(db,user.id,1,20);const lines=orders.map(o=>{const title=planTitle(user,{title_ru:o.title_ru,title_en:o.title_en} as Plan);const status=o.status==='pending'?t(user.language,'pending_order'):o.status==='paid'?t(user.language,'paid_order'):o.status==='expired'?t(user.language,'expired_order'):o.status;return `${title} · ${formatRub(o.amount_minor)} ₽ · ${status}`});return sendOrEditUi(api,db,user,t(user.language,'orders_title')+'\n\n'+(lines.join('\n')||t(user.language,'no_orders')),[[{text:t(user.language,'back'),callback_data:'account:open'}]],[],sourceMessageId)}

export function imageTemplates(lang:Lang){return IMAGE_TEMPLATES.map(x=>({id:x.id,name:x.name[lang],description:x.description[lang]}))}
function parseImageCfg(m:Model){try{return JSON.parse(m.config||'{}') as any}catch{return {}}}
function imageOptions(m:Model){const c=parseImageCfg(m);return {aspects:(c.aspect_ratios as string[]|undefined)??['1:1','16:9','9:16','4:3','3:4'],qualities:(c.qualities as string[]|undefined)??['standard','hd'],defaultAspect:c.default_aspect_ratio??'1:1',defaultQuality:c.default_quality??'standard',supportsInputImage:c.supports_input_image===true,emoji:repo.modelEmoji(m)}}
export async function imageModelScreen(api:TelegramApi,db:D1Database,env:Env,user:User,sourceMessageId?:number){const paused=Number((await repo.getSetting(db,'feature_image'))??1)===0;const models=await repo.listImageModels(db,env);if(paused||!models.length)return sendOrEditUi(api,db,user,t(user.language,'images_title')+'\n\n'+t(user.language,'images_dev'),[[{text:t(user.language,'back_chat'),callback_data:'chat:open'}]],[],sourceMessageId);const rows=models.map(m=>[{text:`${repo.modelEmoji(m)} ${m.name}`,callback_data:`image:model:${encodeURIComponent(m.model_key)}`}]);return sendOrEditUi(api,db,user,t(user.language,'images_title')+'\n\n'+t(user.language,'choose_image_model'),rows,[],sourceMessageId)}
export async function imageSettingsScreen(api:TelegramApi,db:D1Database,env:Env,user:User,modelKey:string,state:any,sourceMessageId?:number){const m=await repo.modelByKey(db,modelKey);if(!m)return imageModelScreen(api,db,env,user,sourceMessageId);const o=imageOptions(m);state.aspect??=o.defaultAspect;state.quality??=o.defaultQuality;state.templateId??=null;state.hasImage=Boolean(state.hasImage);const tpl=state.templateId?IMAGE_TEMPLATES.find(x=>x.id===state.templateId):undefined;const cost=m.cost+(state.hasImage?await repo.imageInputCost(db):0)+(tpl?await repo.templateCost(db,tpl.id,tpl.defaultCost):0);const desc=parseImageCfg(m).description?.[user.language]??parseImageCfg(m).description_ru??parseImageCfg(m).description_en??''; const text=`${t(user.language,'image_settings',{model:m.name,aspect:state.aspect,quality:state.quality,template:tpl?tpl.name[user.language]:'—',input:state.hasImage?t(user.language,'input_ready'):t(user.language,'input_none'),cost})}${desc?`\n\n${escape(desc)}`:''}`;const rows=[[{text:`${t(user.language,'aspect')} · ${state.aspect}`,callback_data:`image:aspect:${encodeURIComponent(modelKey)}`}],[{text:`${t(user.language,'quality')} · ${state.quality}`,callback_data:`image:quality:${encodeURIComponent(modelKey)}`}],[{text:t(user.language,'templates'),callback_data:`image:templates:${encodeURIComponent(modelKey)}`}]];if(o.supportsInputImage){rows.push([{text:state.hasImage?t(user.language,'remove_image'):t(user.language,'add_image'),callback_data:`image:${state.hasImage?'remove':'add'}:${encodeURIComponent(modelKey)}`}]);}rows.push([{text:t(user.language,'continue_image'),callback_data:`image:continue:${encodeURIComponent(modelKey)}`}],[{text:t(user.language,'back'),callback_data:'image:open'}]);if(state.templateId)rows.splice(4,0,[{text:t(user.language,'reset_template'),callback_data:`image:reset_template:${encodeURIComponent(modelKey)}`}]);return sendOrEditUi(api,db,user,text,rows,[],sourceMessageId)}
export async function imageAspectScreen(api:TelegramApi,db:D1Database,env:Env,user:User,modelKey:string,state:any,sourceMessageId?:number){const m=await repo.modelByKey(db,modelKey);if(!m)return;const o=imageOptions(m);const rows=o.aspects.map(a=>[{text:`${state.aspect===a?'✅ ':''}${a}`,callback_data:`image:setaspect:${encodeURIComponent(modelKey)}:${encodeURIComponent(a)}`}]);rows.push([{text:t(user.language,'back'),callback_data:`image:settings:${encodeURIComponent(modelKey)}`}]);return sendOrEditUi(api,db,user,t(user.language,'aspect'),rows,[],sourceMessageId)}
export async function imageQualityScreen(api:TelegramApi,db:D1Database,env:Env,user:User,modelKey:string,state:any,sourceMessageId?:number){const m=await repo.modelByKey(db,modelKey);if(!m)return;const o=imageOptions(m);const rows=o.qualities.map(q=>[{text:`${state.quality===q?'✅ ':''}${q}`,callback_data:`image:setquality:${encodeURIComponent(modelKey)}:${encodeURIComponent(q)}`}]);rows.push([{text:t(user.language,'back'),callback_data:`image:settings:${encodeURIComponent(modelKey)}`}]);return sendOrEditUi(api,db,user,t(user.language,'quality'),rows,[],sourceMessageId)}
export async function imageTemplatesScreen(api:TelegramApi,db:D1Database,env:Env,user:User,modelKey:string,state:any,sourceMessageId?:number){const m=await repo.modelByKey(db,modelKey);if(!m)return;const cfg=repo.modelConfig(m);const supported=Array.isArray(cfg.supported_templates)?cfg.supported_templates.map(String):null;const templates=supported?IMAGE_TEMPLATES.filter(x=>supported.includes(x.id)):IMAGE_TEMPLATES;const rows:any[]=templates.map(x=>[{text:`${state.templateId===x.id?'✅ ':''}${x.name[user.language]}`,callback_data:`image:template:${encodeURIComponent(modelKey)}:${x.id}`}]);rows.push([{text:t(user.language,'back'),callback_data:`image:settings:${encodeURIComponent(modelKey)}`}]);return sendOrEditUi(api,db,user,t(user.language,'templates'),rows,[],sourceMessageId)}
export async function imageTemplateScreen(api:TelegramApi,db:D1Database,env:Env,user:User,modelKey:string,templateId:string,state:any,sourceMessageId?:number){const m=await repo.modelByKey(db,modelKey);const tpl=IMAGE_TEMPLATES.find(x=>x.id===templateId);if(!m||!tpl)return;const cfg=repo.modelConfig(m);if(Array.isArray(cfg.supported_templates)&&!cfg.supported_templates.map(String).includes(templateId)){return imageTemplatesScreen(api,db,env,user,modelKey,state,sourceMessageId)}const tc=await repo.templateCost(db,tpl.id,tpl.defaultCost);const total=m.cost+(state.hasImage?await repo.imageInputCost(db):0)+tc;const text=t(user.language,'template_details',{name:tpl.name[user.language],description:tpl.description[user.language],template_cost:tc,model_cost:m.cost,total});const rows=[[{text:t(user.language,'use'),callback_data:`image:usetemplate:${encodeURIComponent(modelKey)}:${templateId}`}],[{text:t(user.language,'back'),callback_data:`image:templates:${encodeURIComponent(modelKey)}`}]];return sendOrEditUi(api,db,user,text,rows,[],sourceMessageId)}
export async function imageAddImageScreen(api:TelegramApi,db:D1Database,env:Env,user:User,modelKey:string,state:any,sourceMessageId?:number){const m=await repo.modelByKey(db,modelKey);if(!m)return;const o=imageOptions(m);if(!o.supportsInputImage)return imageSettingsScreen(api,db,env,user,modelKey,state,sourceMessageId);const fee=await repo.imageInputCost(db);const text=`<b>${t(user.language,'add_image').replace(/^[^\s]+\s/,'')}</b>\n\n💰 Стоимость добавления изображения: <b>${fee}</b>\n\n${state.templateId?t(user.language,'templates')+': '+(IMAGE_TEMPLATES.find(x=>x.id===state.templateId)?.name[user.language]??'—'):''}`;const rows=[[{text:t(user.language,'use'),callback_data:`image:useinput:${encodeURIComponent(modelKey)}`}],[{text:t(user.language,'templates'),callback_data:`image:templates_input:${encodeURIComponent(modelKey)}`}],[{text:t(user.language,'back'),callback_data:`image:settings:${encodeURIComponent(modelKey)}`}]];return sendOrEditUi(api,db,user,text,rows,[],sourceMessageId)}
